name: data_split
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pip=23.3.1
  - hydra-core=1.3.2
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0      
      - requests==2.24.0
      - pandas=2.1.3
      - scikit-learn==1.0.2
      - scipy==1.7.3   